account = (input ("Please input your bank number: "))
password = (input ("Please input your password: "))
amount = (input ("How much do you want to withdrawl: "))
amount = (input ("How much do you want to withdrawl: "))
print(f"Withdrawl a success you \n You were able to withdraw {amount}")